vich_uploader:
    db_driver: orm

    mappings:
        imageDir:
            uri_prefix: '%app.path.imageDir%'
            upload_destination: '%kernel.project_dir%/public%app.path.imageDir%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer